# Etapa de construção
FROM node:18-alpine AS builder

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos de configuração do projeto
COPY package*.json ./
COPY yarn.lock ./

# Instalar as dependências
RUN yarn install --frozen-lockfile

# Copiar o restante do código do projeto
COPY . .

# Construir a aplicação Next.js
RUN yarn build  # O diretório .next é gerado aqui na raiz

# Etapa de produção
FROM node:18-alpine AS runner

# Definir o diretório de trabalho
WORKDIR /app

# Copiar apenas os arquivos necessários para a execução
COPY package.json ./
COPY yarn.lock ./
COPY --from=builder /app/.next ./.next 
COPY --from=builder /app/public ./public

# Instalar apenas as dependências de produção
RUN yarn install --production --frozen-lockfile

# Expor a porta 3000 (padrão do Next.js)
EXPOSE 3000

# Comando para iniciar a aplicação Next.js
CMD ["npm", "start"]
